[package]
name = "scop"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = "0.18.0"
gl = "0.14.0"
glfw = "0.59.0"
image = "0.25.6"
nalgebra = "0.33.2"

[[bin]]
name = "scop"
path = "main.rs"
